version: "3"

networks:
  demo-net:
    driver: bridge

services:
  postgres-demo:
    image: postgres:9.6
    restart: always
    networks:
      - demo-net
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "demo"]
      interval: 5s
      timeout: 5s
      retries: 5
  course-registration:
      build: ../course-registration
      ports:
      - "8080:8080"
      networks:
      - demo-net
      environment:
        POSTGRES_USER: demo
      depends_on:
        - postgres-demo